team-311/pothole-patrol-web

- package.json
- script/seed.js
- server/db/models/comment.js
- server/db/models/crew.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/pothole.js
- server/db/models/upvote.js
- server/db/models/user.js
- server/db/models/user.spec.js
added these models: 
User,
Pothole,
Order,
Comment,
Crew, 
Upvote
And their associations
> added models!

- script/seed.js
- server/api/users.spec.js
- server/db/models/pothole.js
> Updated models and added sample data to facilitate testing

- package-lock.json
- server/api/potholes.js
> Singlepotholeroute

- server/api/index.js
- server/api/potholes.js
> Potholes route

- script/seed.js
- server/db/models/user.js
added seeding for orders, crews, and users; potholes are associated with orders; 
changed user model to include default values for names because current login form does not have first or last name fields and did not want to create them to be able to log in to see the logged-in users views
> Order seed data

- server/api/potholes.js
- server/db/models/pothole.js
- server/index.js
> Adding post route for potholes to submit a report

- package-lock.json
- package.json
- server/api/potholes.js
Implemented image hosting using Cloudinary (10 GB free tier)
closes #24
> Saving images

- package-lock.json
- server/api/users.js
- server/db/models/index.js
This supports viewing issues on home page of native app for a given user. Also fixes the auth defect encountered earlier
> Implementing user route for potholes/reports

- client/store/potholes.js
> small detail in pothole reducer fixed

- package-lock.json
- package.json
- script/seed.js
- server/api/crews/directions.js
- server/api/crews/index.js
- server/api/crews/orders.js
- server/api/crews/potholes.js
- server/api/middleware.js
- server/db/models/pothole.js
supports the Crew work for Single Order and Directions
> Crew single order

- server/api/orders.js
- server/api/potholes.js
> Fixing odd pagination bug

- package-lock.json
- server/db/models/pothole.js
Method on pothole to create orders for each crew and assign them the highest priority potholes
> Order script

- script/seed.js
- server/db/models/pothole.js
Seed file updates necessary for the native Crew view beta testing
> Updating seed script to setup basic order generation and crew members

- server/api/crews/orders.js
Fixes defect found on Native side when clicking 'Get Started' for a Requested work order
> Eager loading issue with Model.update

- client/components/single-pothole/SinglePotholeComments.js
- package-lock.json
- server/db/models/pothole.js
> Rank pothole by priority

- server/api/crews/directions.js
Supports native Directions restyling
> Modifying directions API route to support styling on native

- client/components/all-pothole/all-pothole.js
- server/db/models/pothole.js
> showing priotity based on ranking

- server/api/potholes.js
- server/api/users.js
> route to get users upvoted potholes

- client/components/all-pothole/all-pothole-small.js
- client/components/all-pothole/all-pothole.js
- client/components/dashboard/dashboard.js
- client/components/dashboard/pothole-list-view.js
- client/components/navbar.js
- client/components/order-list-view.js
- client/components/single-order/PotholeRow.js
- client/routes.js
- client/store/orders.js
- package.json
- public/index.html
- public/style.css
- server/api/orders.js
- server/api/potholes.js
- server/db/models/user.js
- Added proper pagination for Orders and Potholes
- Removed Orders from home page (Cody already has done this in one of his PRs)
- Updated Orders to display crew name and user full name
connects to #75
> Pagination components

- server/api/crews/orders.js
Supports styling refactoring work done on Native
> Added additional calculations for /completed orders route

- client/components/single-pothole/SinglePotholeComments.js
- client/components/single-pothole/SinglePotholeView.js
> adds style to single pothole view

- client/components/single-pothole/SinglePotholeView.js
> changes open icon

- package-lock.json
> Updated package lock
